# Generated by Django 4.1.4 on 2022-12-09 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='helper',
            options={'verbose_name': 'Шпаргалка', 'verbose_name_plural': 'Шпаргалки'},
        ),
    ]
